# Generated by Django 3.1.5 on 2021-01-11 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Марка авто')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена авто')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)], verbose_name='Год выпуска авто')),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате +79999999999', regex='^\\+7\\d{10}$')], verbose_name='Номер телефона продавца')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото авто')),
            ],
        ),
    ]
